# Generated by Django 3.1.2 on 2021-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('rank', models.CharField(max_length=100, null=True)),
                ('coy', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
