# Generated by Django 3.2.3 on 2021-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0004_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(blank=True, null=True)),
                ('fired', models.ImageField(blank=True, null=True, upload_to='')),
                ('detect', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='target_2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ets',
        ),
        migrations.RemoveField(
            model_name='result',
            name='fig2_ly',
        ),
        migrations.RemoveField(
            model_name='result',
            name='fig2_other',
        ),
        migrations.RemoveField(
            model_name='result',
            name='fig3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='result',
            name='ret',
        ),
        migrations.RemoveField(
            model_name='result',
            name='total',
        ),
        migrations.AddField(
            model_name='result',
            name='detect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fired',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='result',
            name='hits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firer',
            name='coy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firer',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firer',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
