# Generated by Django 3.2.3 on 2021-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0005_auto_20210620_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fire',
            name='detect',
        ),
        migrations.AddField(
            model_name='fire',
            name='detected',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
