# Generated by Django 3.2.3 on 2021-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0008_auto_20210621_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
