# Generated by Django 3.2.3 on 2021-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Range', '0009_alter_detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire',
            name='detected_hits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
